volumes:
  postgres-mem-langchain-demo-vol:

services:

  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-mem-langchain-demo-vol:/var/lib/postgresql/data
